"""
orchestrator.planning.kernel_execution_bridge

Bridge between smart_spatial_system capability callables and
geochat_kernel.runtime.PlanExecutor.

This module is intentionally opt-in and experimental for Phase 3.

It does not replace DagExecutor yet.
It provides a kernel-native execution path for QueryPlan objects generated by
orchestrator.planning.kernel_plan_adapter.
"""

from __future__ import annotations

import asyncio
import inspect
from dataclasses import dataclass, field
from typing import Any, Callable

from orchestrator.error_contract import (
    CATEGORY_CAPABILITY_CONTRACT,
    CATEGORY_CAPABILITY_RESOLUTION,
    CATEGORY_KERNEL_EXECUTION,
    CATEGORY_VALIDATION,
    exception_to_error,
    make_error,
)

from geochat_kernel.models.execution_artifact import ExecutionArtifact
from geochat_kernel.models.query_plan import PlanStep, QueryPlan
from geochat_kernel.runtime.app_container import KernelAppContainer
from geochat_kernel.runtime.execution_context import ExecutionContext
from geochat_kernel.runtime.plan_executor import PlanExecutor


CapabilityResolver = Callable[[str], Callable[..., Any]]


@dataclass
class KernelExecutionBridgeResult:
    """
    Structured result for kernel execution bridge runs.

    artifacts:
        Raw kernel ExecutionArtifact objects keyed by step id.

    output_artifacts:
        Output subset based on QueryPlan.metadata["output_nodes"].

    outputs:
        Live/raw values extracted from all artifacts.

    output_nodes:
        Live/raw values extracted from output_artifacts.
    """

    success: bool
    artifacts: dict[str, ExecutionArtifact] = field(default_factory=dict)
    output_artifacts: dict[str, ExecutionArtifact] = field(default_factory=dict)
    outputs: dict[str, Any] = field(default_factory=dict)
    output_nodes: dict[str, Any] = field(default_factory=dict)
    context: ExecutionContext | None = None
    error: str | None = None
    structured_error: dict[str, Any] | None = None


def _is_json_compatible(value: Any) -> bool:
    if value is None or isinstance(value, (str, int, float, bool)):
        return True

    if isinstance(value, list):
        return all(_is_json_compatible(item) for item in value)

    if isinstance(value, dict):
        return all(
            isinstance(key, str) and _is_json_compatible(item)
            for key, item in value.items()
        )

    return False


def _summarize_value(value: Any) -> dict[str, Any]:
    summary: dict[str, Any] = {
        "type": type(value).__name__,
    }

    if isinstance(value, list):
        summary["length"] = len(value)

    if isinstance(value, dict):
        summary["keys"] = sorted(str(key) for key in value.keys())[:30]
        if "features" in value and isinstance(value["features"], list):
            summary["feature_count"] = len(value["features"])

    if hasattr(value, "features"):
        try:
            summary["feature_count"] = len(getattr(value, "features") or [])
        except Exception:
            pass

    if hasattr(value, "metadata"):
        metadata = getattr(value, "metadata")
        if isinstance(metadata, dict):
            for key in ("feature_count", "output_feature_count", "matched_count"):
                if key in metadata:
                    summary[key] = metadata[key]

    return summary


def _artifact_kind_for_step(step: PlanStep, value: Any) -> str:
    produces = step.metadata.get("produces")
    if isinstance(produces, str) and produces:
        return produces

    if isinstance(value, dict) and value.get("type") == "FeatureCollection":
        return "features"

    if isinstance(value, list):
        return "table"

    return "generic"


def value_to_execution_artifact(
    value: Any,
    *,
    step: PlanStep,
    produced_by: str | None = None,
) -> ExecutionArtifact:
    """
    Convert a raw capability output to an ExecutionArtifact.

    We attach the raw value as a live object so downstream kernel steps can
    consume the original Python object without lossy serialization.
    """
    if isinstance(value, ExecutionArtifact):
        return value

    payload: dict[str, Any] = {
        "summary": _summarize_value(value),
    }

    if _is_json_compatible(value):
        payload["data"] = value

    artifact = ExecutionArtifact(
        step_id=step.id,
        kind=_artifact_kind_for_step(step, value),
        payload=payload,
        produced_by=produced_by,
        metadata={
            "source": "smart_spatial_system.kernel_execution_bridge",
            "step_type": step.type,
            "step_name": step.name,
            "capability_name": step.metadata.get("capability_name") or step.type,
        },
    )
    artifact.attach_live(value)
    return artifact


def artifact_to_value(artifact: ExecutionArtifact) -> Any:
    """
    Extract the best raw/live value from an ExecutionArtifact.
    """
    try:
        if getattr(artifact, "has_live", False):
            return artifact.get_live()
    except Exception:
        pass

    try:
        live = artifact.get_live()
        if live is not None:
            return live
    except Exception:
        pass

    payload = artifact.payload or {}
    if "data" in payload:
        return payload["data"]
    if "value" in payload:
        return payload["value"]

    return payload


def _find_missing_external_inputs(
    query_plan: QueryPlan,
    initial_inputs: dict[str, Any],
) -> list[dict[str, str]]:
    """
    Find external inputs required by PlanStep metadata but missing from
    initial_inputs.

    The kernel PlanExecutor only resolves dependency artifacts. External
    request inputs are a bridge concern, so we validate them before executing
    the kernel plan to avoid losing useful details inside wrapped kernel errors.
    """
    missing: list[dict[str, str]] = []

    for step in query_plan.steps:
        external_input_map = step.metadata.get("external_input_map", {})
        if not isinstance(external_input_map, dict):
            continue

        for param_name, input_name in external_input_map.items():
            input_key = str(input_name)
            if input_key not in initial_inputs:
                missing.append(
                    {
                        "step_id": step.id,
                        "step_name": step.name,
                        "step_type": step.type,
                        "param_name": str(param_name),
                        "input_name": input_key,
                    }
                )

    return missing


def _format_missing_external_inputs(
    missing: list[dict[str, str]],
) -> str:
    parts = []
    for item in missing:
        parts.append(
            "step={step_id!r} param={param_name!r} input={input_name!r}".format(
                **item
            )
        )

    return (
        "Missing initial inputs required by kernel plan: "
        + "; ".join(parts)
    )


def _missing_external_inputs_structured_error(
    missing: list[dict[str, str]],
    *,
    message: str,
) -> dict[str, Any]:
    """
    Build a public-safe structured error for missing bridge/runtime inputs.
    """
    return make_error(
        code="kernel_execution.missing_external_inputs",
        message=message,
        category=CATEGORY_VALIDATION,
        retryable=False,
        details={
            "missing_external_inputs": missing,
        },
        source="kernel_execution_bridge",
    ).to_dict()


def _kernel_exception_structured_error(exc: BaseException) -> dict[str, Any]:
    """
    Convert kernel/capability exceptions into the Phase 4 structured error
    contract while preserving the existing plain string error for backward
    compatibility.

    geochat_kernel may wrap capability errors, so classification uses the full
    exception chain when available.
    """
    def _exception_chain(root: BaseException) -> list[BaseException]:
        chain: list[BaseException] = []
        seen: set[int] = set()
        current: BaseException | None = root

        while current is not None and id(current) not in seen:
            chain.append(current)
            seen.add(id(current))

            cause = getattr(current, "__cause__", None)
            context = getattr(current, "__context__", None)

            if isinstance(cause, BaseException):
                current = cause
            elif isinstance(context, BaseException):
                current = context
            else:
                current = None

        return chain

    chain = _exception_chain(exc)

    for item in chain:
        existing_structured_error = getattr(item, "structured_error", None)
        if isinstance(existing_structured_error, dict):
            return dict(existing_structured_error)

    chain_details = [
        {
            "type": type(item).__name__,
            "message": str(item) or type(item).__name__,
        }
        for item in chain
    ]

    combined_message = " | ".join(
        str(item) or type(item).__name__
        for item in chain
    ).lower()

    type_names = {type(item).__name__ for item in chain}

    code = "kernel_execution.failed"
    category = CATEGORY_KERNEL_EXECUTION

    # Best-effort classification. This is intentionally conservative and
    # additive; it does not change exception behavior.
    if (
        "no handler" in combined_message
        or "missing required capabilities" in combined_message
        or "could not find required capabilities" in combined_message
        or (
            "capability" in combined_message
            and (
                "not found" in combined_message
                or "missing" in combined_message
                or "resolve" in combined_message
                or "resolution" in combined_message
            )
        )
    ):
        code = "capability.resolution_failed"
        category = CATEGORY_CAPABILITY_RESOLUTION
    elif (
        "TypeError" in type_names
        or "ValidationError" in type_names
        or "unexpected keyword" in combined_message
        or "got an unexpected" in combined_message
        or "missing required" in combined_message
        or "missing_properties" in combined_message
        or "missing properties" in combined_message
        or "signature" in combined_message
        or "parameter" in combined_message
        or "parameters" in combined_message
    ):
        code = "capability.contract_failed"
        category = CATEGORY_CAPABILITY_CONTRACT

    # If a wrapped kernel error hides the actual inner exception, keep the top
    # error generic. When the chain exposes a contract/resolution signal, the
    # classification above will choose the more specific code.
    primary_exception_type = (
        type(chain[-1]).__name__
        if len(chain) > 1 and code != "kernel_execution.failed"
        else type(exc).__name__
    )

    return exception_to_error(
        exc,
        code=code,
        category=category,
        retryable=False,
        source="kernel_execution_bridge",
        details={
            "exception_type": primary_exception_type,
            "exception_chain": chain_details,
        },
    ).to_dict()


class CapabilityStepHandler:
    """
    Kernel StepHandler adapter for existing smart_spatial_system capabilities.

    It is intentionally duck-typed to the kernel BaseStepHandler contract:
      - name
      - priority
      - handled_types
      - match_score(step)
      - async handle(step, inputs, context)

    The actual capability function is resolved from:
      step.metadata["capability_name"] or step.type
    """

    name = "smart_spatial_system.capability_step_handler"
    priority = 100
    handled_types: set[str] = set()

    def __init__(
        self,
        capability_resolver: CapabilityResolver,
    ) -> None:
        self.capability_resolver = capability_resolver

    def match_score(self, step: PlanStep) -> float:
        capability_name = step.metadata.get("capability_name") or step.type
        if not capability_name:
            return 0.0

        try:
            self.capability_resolver(str(capability_name))
        except Exception:
            return 0.0

        return 1.0

    async def handle(
        self,
        step: PlanStep,
        inputs: dict[str, ExecutionArtifact],
        context: ExecutionContext,
    ) -> ExecutionArtifact:
        capability_name = str(step.metadata.get("capability_name") or step.type)
        capability_fn = self.capability_resolver(capability_name)

        kwargs: dict[str, Any] = {}

        # 1. Static parameters generated by the planner.
        kwargs.update(step.parameters)

        # 2. Literal DagNode.inputs that were not references.
        literal_inputs = step.metadata.get("literal_inputs", {})
        if isinstance(literal_inputs, dict):
            kwargs.update(literal_inputs)

        # 3. External initial inputs preserved by the DagPlan -> QueryPlan adapter.
        initial_inputs = context.metadata.get("initial_inputs", {})
        external_input_map = step.metadata.get("external_input_map", {})
        if isinstance(initial_inputs, dict) and isinstance(external_input_map, dict):
            for param_name, input_name in external_input_map.items():
                if input_name not in initial_inputs:
                    raise KeyError(
                        f"Initial input {input_name!r} required by step "
                        f"{step.id!r} parameter {param_name!r} was not provided."
                    )
                kwargs[str(param_name)] = initial_inputs[input_name]

        # 4. Dependency artifacts resolved by kernel PlanExecutor.
        for param_name, artifact in inputs.items():
            kwargs[param_name] = artifact_to_value(artifact)

        output = capability_fn(**kwargs)
        if inspect.isawaitable(output):
            output = await output

        return value_to_execution_artifact(
            output,
            step=step,
            produced_by=self.name,
        )


def make_kernel_container_for_capabilities(
    capability_resolver: CapabilityResolver,
) -> KernelAppContainer:
    """
    Create a minimal KernelAppContainer with one bridge StepHandler.
    """
    container = KernelAppContainer()
    container.step_handlers.register_handler(
        CapabilityStepHandler(capability_resolver),
        replace=True,
    )
    return container


async def execute_kernel_plan_with_capabilities(
    query_plan: QueryPlan,
    *,
    capability_resolver: CapabilityResolver,
    initial_inputs: dict[str, Any] | None = None,
    context: ExecutionContext | None = None,
    raise_on_error: bool = False,
) -> KernelExecutionBridgeResult:
    """
    Execute a kernel QueryPlan using existing smart_spatial_system capabilities.

    This is the async bridge around geochat_kernel.runtime.PlanExecutor.
    """
    initial_inputs = initial_inputs or {}

    context = context or ExecutionContext(
        raw_text=str(query_plan.metadata.get("raw_query") or ""),
        language=str(query_plan.metadata.get("language") or "unknown"),
        metadata={},
    )
    context.metadata.setdefault("initial_inputs", initial_inputs)
    context.metadata.setdefault("kernel_plan_id", query_plan.id)
    context.metadata.setdefault("query_ir_id", query_plan.query_ir_id)
    context.metadata.setdefault("bridge", "smart_spatial_system.kernel_execution_bridge")

    missing_external_inputs = _find_missing_external_inputs(
        query_plan,
        initial_inputs,
    )
    if missing_external_inputs:
        error = _format_missing_external_inputs(missing_external_inputs)
        context.metadata["missing_external_inputs"] = missing_external_inputs

        if raise_on_error:
            raise KeyError(error)

        return KernelExecutionBridgeResult(
            success=False,
            artifacts={},
            output_artifacts={},
            outputs={},
            output_nodes={},
            context=context,
            error=error,
            structured_error=_missing_external_inputs_structured_error(
                missing_external_inputs,
                message=error,
            ),
        )

    container = make_kernel_container_for_capabilities(capability_resolver)
    executor = PlanExecutor(container)

    try:
        artifacts = await executor.execute(query_plan, context)
    except Exception as exc:
        if raise_on_error:
            raise
        return KernelExecutionBridgeResult(
            success=False,
            artifacts={},
            output_artifacts={},
            outputs={},
            output_nodes={},
            context=context,
            error=str(exc),
            structured_error=_kernel_exception_structured_error(exc),
        )

    output_node_ids = [
        str(node_id)
        for node_id in query_plan.metadata.get("output_nodes", [])
    ]

    output_artifacts = {
        node_id: artifacts[node_id]
        for node_id in output_node_ids
        if node_id in artifacts
    }

    outputs = {
        step_id: artifact_to_value(artifact)
        for step_id, artifact in artifacts.items()
    }

    output_nodes = {
        step_id: artifact_to_value(artifact)
        for step_id, artifact in output_artifacts.items()
    }

    return KernelExecutionBridgeResult(
        success=True,
        artifacts=artifacts,
        output_artifacts=output_artifacts,
        outputs=outputs,
        output_nodes=output_nodes,
        context=context,
        error=None,
        structured_error=None,
    )


def execute_kernel_plan_with_capabilities_sync(
    query_plan: QueryPlan,
    *,
    capability_resolver: CapabilityResolver,
    initial_inputs: dict[str, Any] | None = None,
    context: ExecutionContext | None = None,
    raise_on_error: bool = False,
) -> KernelExecutionBridgeResult:
    """
    Synchronous convenience wrapper for scripts/tests.

    Do not call this from an already-running event loop.
    """
    return asyncio.run(
        execute_kernel_plan_with_capabilities(
            query_plan,
            capability_resolver=capability_resolver,
            initial_inputs=initial_inputs,
            context=context,
            raise_on_error=raise_on_error,
        )
    )


def _artifact_has_live(artifact: ExecutionArtifact) -> bool:
    try:
        return bool(getattr(artifact, "has_live", False))
    except Exception:
        pass

    try:
        return artifact.get_live() is not None
    except Exception:
        return False


def execution_artifact_to_summary(
    artifact: ExecutionArtifact,
) -> dict[str, Any]:
    """
    Build a compact public-safe summary for one ExecutionArtifact.

    This intentionally excludes:
      - live object
      - full payload data
      - large refs
    """
    payload = artifact.payload or {}
    metadata = artifact.metadata or {}

    summary: dict[str, Any] = {
        "id": artifact.id,
        "step_id": artifact.step_id,
        "kind": artifact.kind,
        "produced_by": artifact.produced_by,
        "is_remote": bool(artifact.is_remote),
        "has_live": _artifact_has_live(artifact),
        "payload_keys": sorted(str(key) for key in payload.keys()),
        "metadata_keys": sorted(str(key) for key in metadata.keys()),
    }

    if "summary" in payload and isinstance(payload["summary"], dict):
        summary["payload_summary"] = payload["summary"]

    for key in (
        "source",
        "step_type",
        "step_name",
        "capability_name",
        "cache_hit",
    ):
        if key in metadata:
            summary[key] = metadata[key]

    if artifact.confidence is not None:
        summary["confidence"] = artifact.confidence

    if artifact.refs:
        summary["ref_count"] = len(artifact.refs)

    return summary


def kernel_execution_to_summary(
    result: KernelExecutionBridgeResult | None,
) -> dict[str, Any] | None:
    """
    Build a compact public-safe summary for optional kernel execution.

    Intended for response metadata/debug visibility.
    """
    if result is None:
        return None

    artifacts = result.artifacts or {}
    output_artifacts = result.output_artifacts or {}

    return {
        "success": bool(result.success),
        "error": result.error,
        "structured_error": result.structured_error,
        "artifact_count": len(artifacts),
        "output_artifact_count": len(output_artifacts),
        "artifact_ids": list(artifacts.keys()),
        "output_artifact_ids": list(output_artifacts.keys()),
        "artifacts": [
            execution_artifact_to_summary(artifact)
            for _, artifact in artifacts.items()
        ],
        "output_artifacts": [
            execution_artifact_to_summary(artifact)
            for _, artifact in output_artifacts.items()
        ],
        "context": (
            {
                "request_id": result.context.request_id,
                "language": result.context.language,
                "kernel_plan_id": result.context.metadata.get("kernel_plan_id"),
                "query_ir_id": result.context.metadata.get("query_ir_id"),
                "bridge": result.context.metadata.get("bridge"),
            }
            if result.context is not None
            else None
        ),
    }


def _normalize_output_for_comparison(value: Any) -> Any:
    """
    Normalize common planning/kernel output objects into JSON-like structures
    suitable for stable equality comparison.

    This intentionally avoids exposing heavy/live objects in public metadata.
    """
    if value is None or isinstance(value, (str, int, float, bool)):
        return value

    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        try:
            return _normalize_output_for_comparison(model_dump())
        except Exception:
            pass

    geojson = getattr(value, "geojson", None)
    if isinstance(geojson, dict):
        return _normalize_output_for_comparison(geojson)

    features = getattr(value, "features", None)
    if isinstance(features, list):
        return {
            "type": "FeatureCollection",
            "features": _normalize_output_for_comparison(features),
        }

    if isinstance(value, dict):
        return {
            str(key): _normalize_output_for_comparison(item)
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        }

    if isinstance(value, (list, tuple)):
        return [_normalize_output_for_comparison(item) for item in value]

    return repr(value)


def _stable_output_fingerprint(value: Any) -> str:
    import json

    normalized = _normalize_output_for_comparison(value)

    try:
        return json.dumps(
            normalized,
            ensure_ascii=False,
            sort_keys=True,
            default=str,
        )
    except Exception:
        return repr(normalized)


def compare_kernel_execution_to_planning_outputs(
    planning_result: Any,
) -> dict[str, Any]:
    """
    Compare current DAG planning outputs with optional kernel execution outputs.

    The returned summary is public/debug-safe and does not include the actual
    payloads or live objects.
    """
    dag_output_nodes = getattr(planning_result, "output_nodes", None) or {}
    kernel_execution = getattr(planning_result, "kernel_execution", None)

    if kernel_execution is None:
        return {
            "available": False,
            "success": None,
            "dag_success": bool(getattr(planning_result, "success", False)),
            "kernel_success": None,
            "matching_output_node_ids": None,
            "output_values_match": None,
            "dag_output_node_ids": sorted(str(key) for key in dag_output_nodes.keys()),
            "kernel_output_node_ids": [],
            "missing_in_kernel": [],
            "extra_in_kernel": [],
            "mismatched_outputs": [],
        }

    kernel_output_nodes = getattr(kernel_execution, "output_nodes", None) or {}

    dag_ids = sorted(str(key) for key in dag_output_nodes.keys())
    kernel_ids = sorted(str(key) for key in kernel_output_nodes.keys())

    dag_id_set = set(dag_ids)
    kernel_id_set = set(kernel_ids)

    missing_in_kernel = sorted(dag_id_set - kernel_id_set)
    extra_in_kernel = sorted(kernel_id_set - dag_id_set)

    mismatched_outputs: list[dict[str, Any]] = []

    for node_id in sorted(dag_id_set & kernel_id_set):
        dag_value = dag_output_nodes[node_id]
        kernel_value = kernel_output_nodes[node_id]

        dag_fingerprint = _stable_output_fingerprint(dag_value)
        kernel_fingerprint = _stable_output_fingerprint(kernel_value)

        if dag_fingerprint != kernel_fingerprint:
            mismatched_outputs.append(
                {
                    "node_id": node_id,
                    "dag_type": type(dag_value).__name__,
                    "kernel_type": type(kernel_value).__name__,
                }
            )

    matching_output_node_ids = not missing_in_kernel and not extra_in_kernel
    output_values_match = not mismatched_outputs

    success = (
        bool(getattr(planning_result, "success", False))
        and bool(getattr(kernel_execution, "success", False))
        and matching_output_node_ids
        and output_values_match
    )

    return {
        "available": True,
        "success": success,
        "dag_success": bool(getattr(planning_result, "success", False)),
        "kernel_success": bool(getattr(kernel_execution, "success", False)),
        "matching_output_node_ids": matching_output_node_ids,
        "output_values_match": output_values_match,
        "dag_output_node_ids": dag_ids,
        "kernel_output_node_ids": kernel_ids,
        "missing_in_kernel": missing_in_kernel,
        "extra_in_kernel": extra_in_kernel,
        "mismatched_outputs": mismatched_outputs,
    }
