#!/usr/bin/env python3
"""
Plugin Agent CLI for geoChat-v2-core system.
Generates plugin code, configs, and tests from plugin specs JSON.
"""

import argparse
import json
import os
import sys
import time
import hashlib
import zipfile
import shutil
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field, asdict
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Constants
DEFAULT_MODEL_CHEAP = "gpt-4o-mini"
DEFAULT_MODEL_STRONG = "gpt-4o"
MAX_FIX_ITERATIONS = 3
CHECKPOINT_INTERVAL = 10
OUTPUT_DIR = Path("output")
PLUGINS_DIR = OUTPUT_DIR / "backend" / "components" / "plugins"
CONFIG_DIR = OUTPUT_DIR / "backend" / "config" / "plugins"
TESTS_DIR = OUTPUT_DIR / "tests"
DOWNLOADS_DIR = OUTPUT_DIR / "downloads"
CHECKPOINT_FILE = OUTPUT_DIR / "checkpoint.json"
REPORT_FILE = OUTPUT_DIR / "report.md"

# SDK templates
PLUGIN_TEMPLATE = '''"""Plugin: {plugin_id} - {description}"""
from geochat_sdk.decorators import capability
from geochat_sdk.exceptions import SDKDependencyError
from geochat_sdk.plugin import auto_collect
from geochat_sdk.types.vector import VectorOut
from geochat_sdk.types.raster import RasterOut
from _shared.plugin_config import get_config

{imports}

@capability(
    keywords={keywords},
    description="{description}",
    required_inputs={required_inputs},
    optional_inputs={optional_inputs},
    output_kind="{output_kind}",
    metadata={metadata}
)
def {function_name}({function_params}) -> {return_type}:
    \"\"\"{function_docstring}\"\"\"
    config = get_config("{plugin_id}")
    {function_body}

PLUGIN = auto_collect(
    id="{plugin_id}",
    version="{version}",
    name="{name}",
    description="{description}",
    author="{author}",
    permissions={permissions}
)
'''

CONFIG_TEMPLATE = """# Configuration for {plugin_id}
# Generated by Plugin Agent
{config_content}
"""

EXAMPLE_CONFIG_TEMPLATE = """# Example configuration for {plugin_id}
# This file serves as a reference for configuring the plugin
{example_config}
"""

TEST_TEMPLATE = '''"""Tests for {plugin_id} plugin"""
import pytest
from backend.components.plugins.{plugin_id} import {function_name}

def test_{function_name}_basic():
    """Test basic functionality"""
    result = {function_name}({test_params})
    assert result is not None
    assert hasattr(result, "data")

def test_{function_name}_with_config():
    """Test with configuration"""
    result = {function_name}({test_params})
    assert result is not None

def test_{function_name}_error_handling():
    """Test error handling"""
    with pytest.raises(Exception):
        {function_name}(invalid_input=None)
'''

@dataclass
class PluginSpec:
    """Plugin specification from JSON input"""
    plugin_id: str
    name: str
    description: str
    author: str
    version: str
    keywords: List[str]
    required_inputs: List[str]
    optional_inputs: List[str]
    output_kind: str
    metadata: Dict[str, Any]
    function_name: str
    function_params: str
    function_docstring: str
    function_body: str
    imports: str
    return_type: str
    permissions: List[str]
    config_content: str
    example_config: str
    test_params: str

@dataclass
class PluginResult:
    """Result of plugin generation"""
    plugin_id: str
    status: str  # passed, failed, skipped
    error: Optional[str] = None
    cost: float = 0.0
    iterations: int = 0
    files_generated: List[str] = field(default_factory=list)

@dataclass
class Checkpoint:
    """Checkpoint state"""
    processed_plugins: List[str] = field(default_factory=list)
    results: List[Dict] = field(default_factory=list)
    total_cost: float = 0.0
    start_time: float = 0.0

class LLMClient:
    """Client for LLM API calls"""
    
    def __init__(self, model: str, api_key: str = None, base_url: str = None):
        self.model = model
        self.api_key = api_key or os.getenv("LLM_API_KEY")
        self.base_url = base_url or os.getenv("LLM_BASE_URL", "https://api.openai.com/v1")
        self.cache: Dict[str, str] = {}
        
        if not self.api_key:
            raise ValueError("LLM_API_KEY not set")
    
    def _get_cache_key(self, messages: List[Dict]) -> str:
        """Generate MD5 cache key from messages"""
        content = json.dumps(messages, sort_keys=True)
        return hashlib.md5(content.encode()).hexdigest()
    
    def call(self, messages: List[Dict], stream: bool = False, temperature: float = 0.7) -> str:
        """Make LLM API call with caching"""
        cache_key = self._get_cache_key(messages)
        
        if cache_key in self.cache:
            return self.cache[cache_key]
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": temperature,
            "stream": stream
        }
        
        try:
            response = requests.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=payload,
                stream=stream
            )
            response.raise_for_status()
            
            if stream:
                content = ""
                for line in response.iter_lines():
                    if line:
                        try:
                            data = json.loads(line.decode().removeprefix("data: "))
                            if "choices" in data:
                                delta = data["choices"][0].get("delta", {})
                                content += delta.get("content", "")
                        except (json.JSONDecodeError, KeyError):
                            continue
            else:
                content = response.json()["choices"][0]["message"]["content"]
            
            self.cache[cache_key] = content
            return content
            
        except requests.exceptions.RequestException as e:
            raise RuntimeError(f"LLM API call failed: {e}")

class PluginAgent:
    """Main plugin generation agent"""
    
    def __init__(self, args: argparse.Namespace):
        self.args = args
        self.verbose = args.verbose
        self.dry_run = args.dry_run
        self.max_plugins = args.max_plugins
        
        # Initialize LLM clients
        self.cheap_llm = LLMClient(args.model_cheap)
        self.strong_llm = LLMClient(args.model_strong)
        
        # State
        self.checkpoint = Checkpoint()
        self.results: List[PluginResult] = []
        self.total_cost = 0.0
        self.start_time = time.time()
        
        # Create output directories
        for directory in [PLUGINS_DIR, CONFIG_DIR, TESTS_DIR, DOWNLOADS_DIR]:
            directory.mkdir(parents=True, exist_ok=True)
    
    def load_plugin_specs(self, json_path: str) -> List[PluginSpec]:
        """Load plugin specs from JSON file"""
        with open(json_path, 'r') as f:
            data = json.load(f)
        
        specs = []
        for item in data.get("plugins", data if isinstance(data, list) else [data]):
            spec = PluginSpec(
                plugin_id=item.get("plugin_id", item.get("id", "")),
                name=item.get("name", ""),
                description=item.get("description", ""),
                author=item.get("author", "geoChat"),
                version=item.get("version", "1.0.0"),
                keywords=item.get("keywords", []),
                required_inputs=item.get("required_inputs", []),
                optional_inputs=item.get("optional_inputs", []),
                output_kind=item.get("output_kind", "vector"),
                metadata=item.get("metadata", {}),
                function_name=item.get("function_name", ""),
                function_params=item.get("function_params", ""),
                function_docstring=item.get("function_docstring", ""),
                function_body=item.get("function_body", ""),
                imports=item.get("imports", ""),
                return_type=item.get("return_type", "VectorOut"),
                permissions=item.get("permissions", []),
                config_content=item.get("config_content", ""),
                example_config=item.get("example_config", ""),
                test_params=item.get("test_params", "")
            )
            specs.append(spec)
        
        return specs
    
    def generate_spec_yaml(self, plugin_spec: PluginSpec) -> str:
        """Generate spec YAML using cheap model"""
        if self.dry_run:
            return f"# Dry run: spec YAML for {plugin_spec.plugin_id}"
        
        messages = [
            {"role": "system", "content": "You are a plugin specification generator for geoChat system. Generate YAML configuration for the given plugin."},
            {"role": "user", "content": f"Generate a complete YAML configuration for plugin '{plugin_spec.plugin_id}':\nName: {plugin_spec.name}\nDescription: {plugin_spec.description}\nKeywords: {plugin_spec.keywords}\nRequired inputs: {plugin_spec.required_inputs}\nOptional inputs: {plugin_spec.optional_inputs}\nOutput kind: {plugin_spec.output_kind}\n\nReturn only the YAML content."}
        ]
        
        return self.cheap_llm.call(messages)
    
    def generate_plugin_code(self, plugin_spec: PluginSpec) -> str:
        """Generate plugin code using strong model"""
        if self.dry_run:
            return PLUGIN_TEMPLATE.format(
                plugin_id=plugin_spec.plugin_id,
                description=plugin_spec.description,
                imports=plugin_spec.imports,
                keywords=json.dumps(plugin_spec.keywords),
                required_inputs=json.dumps(plugin_spec.required_inputs),
                optional_inputs=json.dumps(plugin_spec.optional_inputs),
                output_kind=plugin_spec.output_kind,
                metadata=json.dumps(plugin_spec.metadata),
                function_name=plugin_spec.function_name,
                function_params=plugin_spec.function_params,
                return_type=plugin_spec.return_type,
                function_docstring=plugin_spec.function_docstring,
                function_body=plugin_spec.function_body,
                version=plugin_spec.version,
                name=plugin_spec.name,
                author=plugin_spec.author,
                permissions=json.dumps(plugin_spec.permissions)
            )
        
        messages = [
            {"role": "system", "content": "You are a plugin code generator for geoChat system. Generate complete Python code using geochat_sdk."},
            {"role": "user", "content": f"Generate Python code for plugin '{plugin_spec.plugin_id}':\n{json.dumps(asdict(plugin_spec), indent=2)}\n\nUse the following template structure:\n{PLUGIN_TEMPLATE}\n\nReturn only the Python code."}
        ]
        
        return self.strong_llm.call(messages)
    
    def generate_config_files(self, plugin_spec: PluginSpec) -> tuple:
        """Generate config and example config files"""
        if self.dry_run:
            return (
                CONFIG_TEMPLATE.format(plugin_id=plugin_spec.plugin_id, config_content=plugin_spec.config_content),
                EXAMPLE_CONFIG_TEMPLATE.format(plugin_id=plugin_spec.plugin_id, example_config=plugin_spec.example_config)
            )
        
        messages = [
            {"role": "system", "content": "Generate YAML configuration files for a geoChat plugin."},
            {"role": "user", "content": f"Generate config YAML and example config YAML for plugin '{plugin_spec.plugin_id}':\n{json.dumps(asdict(plugin_spec), indent=2)}\n\nReturn both files separated by '---CONFIG---' and '---EXAMPLE---' markers."}
        ]
        
        response = self.strong_llm.call(messages)
        parts = response.split("---CONFIG---")
        config = parts[0].strip() if len(parts) > 1 else CONFIG_TEMPLATE.format(plugin_id=plugin_spec.plugin_id, config_content=plugin_spec.config_content)
        
        parts = response.split("---EXAMPLE---")
        example = parts[-1].strip() if len(parts) > 1 else EXAMPLE_CONFIG_TEMPLATE.format(plugin_id=plugin_spec.plugin_id, example_config=plugin_spec.example_config)
        
        return config, example
    
    def generate_tests(self, plugin_spec: PluginSpec) -> str:
        """Generate test file"""
        if self.dry_run:
            return TEST_TEMPLATE.format(
                plugin_id=plugin_spec.plugin_id,
                function_name=plugin_spec.function_name,
                test_params=plugin_spec.test_params
            )
        
        messages = [
            {"role": "system", "content": "Generate pytest test file for a geoChat plugin."},
            {"role": "user", "content": f"Generate pytest tests for plugin '{plugin_spec.plugin_id}':\n{json.dumps(asdict(plugin_spec), indent=2)}\n\nUse this template:\n{TEST_TEMPLATE}\n\nReturn only the Python test code."}
        ]
        
        return self.strong_llm.call(messages)
    
    def write_files(self, plugin_spec: PluginSpec, plugin_code: str, config: str, example_config: str, tests: str) -> List[str]:
        """Write generated files to disk"""
        files = []
        
        # Plugin code
        plugin_path = PLUGINS_DIR / f"{plugin_spec.plugin_id}.py"
        with open(plugin_path, 'w') as f:
            f.write(plugin_code)
        files.append(str(plugin_path))
        
        # Config
        config_path = CONFIG_DIR / f"{plugin_spec.plugin_id}.yaml"
        with open(config_path, 'w') as f:
            f.write(config)
        files.append(str(config_path))
        
        # Example config
        example_path = CONFIG_DIR / f"{plugin_spec.plugin_id}.example.yaml"
        with open(example_path, 'w') as f:
            f.write(example_config)
        files.append(str(example_path))
        
        # Tests
        test_path = TESTS_DIR / f"test_{plugin_spec.plugin_id}.py"
        with open(test_path, 'w') as f:
            f.write(tests)
        files.append(str(test_path))
        
        return files
    
    def run_tests(self, plugin_id: str) -> bool:
        """Run pytest for a specific plugin"""
        if self.dry_run:
            return True
        
        test_file = TESTS_DIR / f"test_{plugin_id}.py"
        if not test_file.exists():
            return False
        
        import subprocess
        result = subprocess.run(
            [sys.executable, "-m", "pytest", str(test_file), "-v", "--tb=short"],
            capture_output=True,
            text=True,
            cwd=OUTPUT_DIR.parent
        )
        
        if self.verbose:
            print(result.stdout)
            if result.stderr:
                print(f"STDERR: {result.stderr}")
        
        return result.returncode == 0
    
    def fix_errors(self, plugin_spec: PluginSpec, error_msg: str) -> Optional[str]:
        """Attempt to fix errors using LLM"""
        messages = [
            {"role": "system", "content": "You are a code fixer for geoChat plugins. Fix the following error."},
            {"role": "user", "content": f"Plugin '{plugin_spec.plugin_id}' has the following error:\n{error_msg}\n\nCurrent code:\n{PLUGIN_TEMPLATE.format(plugin_id=plugin_spec.plugin_id, description=plugin_spec.description, imports=plugin_spec.imports, keywords=json.dumps(plugin_spec.keywords), required_inputs=json.dumps(plugin_spec.required_inputs), optional_inputs=json.dumps(plugin_spec.optional_inputs), output_kind=plugin_spec.output_kind, metadata=json.dumps(plugin_spec.metadata), function_name=plugin_spec.function_name, function_params=plugin_spec.function_params, return_type=plugin_spec.return_type, function_docstring=plugin_spec.function_docstring, function_body=plugin_spec.function_body, version=plugin_spec.version, name=plugin_spec.name, author=plugin_spec.author, permissions=json.dumps(plugin_spec.permissions))}\n\nReturn the fixed code only."}
        ]
        
        return self.strong_llm.call(messages)
    
    def create_zip(self, plugin_id: str, files: List[str]):
        """Create ZIP archive of generated files"""
        zip_path = DOWNLOADS_DIR / f"{plugin_id}.zip"
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
            for file_path in files:
                arcname = os.path.relpath(file_path, str(OUTPUT_DIR))
                zf.write(file_path, arcname)
        
        if self.verbose:
            print(f"Created ZIP: {zip_path}")
    
    def save_checkpoint(self):
        """Save checkpoint state"""
        checkpoint_data = {
            "processed_plugins": self.checkpoint.processed_plugins,
            "results": [asdict(r) for r in self.results],
            "total_cost": self.total_cost,
            "start_time": self.start_time
        }
        
        with open(CHECKPOINT_FILE, 'w') as f:
            json.dump(checkpoint_data, f, indent=2)
    
    def load_checkpoint(self) -> bool:
        """Load checkpoint state if exists"""
        if not CHECKPOINT_FILE.exists():
            return False
        
        with open(CHECKPOINT_FILE, 'r') as f:
            data = json.load(f)
        
        self.checkpoint = Checkpoint(
            processed_plugins=data.get("processed_plugins", []),
            results=[PluginResult(**r) for r in data.get("results", [])],
            total_cost=data.get("total_cost", 0.0),
            start_time=data.get("start_time", time.time())
        )
        
        return True
    
    def generate_report(self):
        """Generate final report as MD file"""
        passed = sum(1 for r in self.results if r.status == "passed")
        failed = sum(1 for r in self.results if r.status == "failed")
        skipped = sum(1 for r in self.results if r.status == "skipped")
        total_time = time.time() - self.start_time
        
        report = f"""# Plugin Generation Report

## Summary
- **Total plugins processed:** {len(self.results)}
- **Passed:** {passed}
- **Failed:** {failed}
- **Skipped:** {skipped}
- **Total time:** {total_time:.2f}s
- **Total cost:** ${self.total_cost:.4f}

## Details

| Plugin ID | Status | Iterations | Cost |
|-----------|--------|------------|------|
"""
        for r in self.results:
            report += f"| {r.plugin_id} | {r.status} | {r.iterations} | ${r.cost:.4f} |\n"
        
        if failed > 0:
            report += "\n## Errors\n\n"
            for r in self.results:
                if r.status == "failed" and r.error:
                    report += f"### {r.plugin_id}\n```\n{r.error}\n```\n\n"
        
        report += f"\n*Generated at: {datetime.now().isoformat()}*"
        
        with open(REPORT_FILE, 'w') as f:
            f.write(report)
        
        if self.verbose:
            print(f"Report saved to {REPORT_FILE}")
    
    def process_plugin(self, plugin_spec: PluginSpec) -> PluginResult:
        """Process a single plugin"""
        result = PluginResult(plugin_id=plugin_spec.plugin_id)
        
        if self.verbose:
            print(f"\nProcessing plugin: {plugin_spec.plugin_id}")
        
        try:
            # Generate spec YAML
            if self.verbose:
                print("  Generating spec YAML...")
            spec_yaml = self.generate_spec_yaml(plugin_spec)
            result.cost += 0.001  # Approximate cost
            
            # Generate plugin code
            if self.verbose:
                print("  Generating plugin code...")
            plugin_code = self.generate_plugin_code(plugin_spec)
            result.cost += 0.01  # Approximate cost
            
            # Generate config files
            if self.verbose:
                print("  Generating config files...")
            config, example_config = self.generate_config_files(plugin_spec)
            result.cost += 0.005  # Approximate cost
            
            # Generate tests
            if self.verbose:
                print("  Generating tests...")
            tests = self.generate_tests(plugin_spec)
            result.cost += 0.005  # Approximate cost
            
            # Write files
            files = self.write_files(plugin_spec, plugin_code, config, example_config, tests)
            result.files_generated = files
            
            # Run tests with auto-fix loop
            if not self.dry_run:
                for iteration in range(MAX_FIX_ITERATIONS):
                    if self.verbose:
                        print(f"  Running tests (iteration {iteration + 1})...")
                    
                    if self.run_tests(plugin_spec.plugin_id):
                        result.status = "passed"
                        result.iterations = iteration + 1
                        break
                    else:
                        if iteration < MAX_FIX_ITERATIONS - 1:
                            if self.verbose:
                                print("  Attempting to fix errors...")
                            # Get error message from test output
                            error_msg = "Tests failed"
                            fixed_code = self.fix_errors(plugin_spec, error_msg)
                            if fixed_code:
                                plugin_code = fixed_code
                                # Rewrite plugin file
                                with open(PLUGINS_DIR / f"{plugin_spec.plugin_id}.py", 'w') as f:
                                    f.write(plugin_code)
                                result.cost += 0.01
                        else:
                            result.status = "failed"
                            result.error = "Max fix iterations reached"
                            result.iterations = iteration + 1
            else:
                result.status = "passed"
            
            # Create ZIP
            if not self.dry_run and result.status == "passed":
                self.create_zip(plugin_spec.plugin_id, files)
            
            self.total_cost += result.cost
            
        except Exception as e:
            result.status = "failed"
            result.error = str(e)
            if self.verbose:
                print(f"  Error: {e}")
        
        return result
    
    def run(self, json_path: str):
        """Main execution flow"""
        # Load checkpoint if resuming
        if self.args.resume and self.load_checkpoint():
            if self.verbose:
                print(f"Resuming from checkpoint with {len(self.checkpoint.processed_plugins)} processed plugins")
        
        # Load plugin specs
        specs = self.load_plugin_specs(json_path)
        
        # Apply max plugins limit
        if self.max_plugins:
            specs = specs[:self.max_plugins]
        
        # Filter out already processed plugins
        specs_to_process = [s for s in specs if s.plugin_id not in self.checkpoint.processed_plugins]
        
        if self.verbose:
            print(f"Total specs: {len(specs)}")
            print(f"Already processed: {len(self.checkpoint.processed_plugins)}")
            print(f"To process: {len(specs_to_process)}")
        
        # Process plugins
        for i, spec in enumerate(specs_to_process):
            result = self.process_plugin(spec)
            self.results.append(result)
            self.checkpoint.processed_plugins.append(spec.plugin_id)
            
            # Save checkpoint periodically
            if (i + 1) % CHECKPOINT_INTERVAL == 0:
                self.save_checkpoint()
                if self.verbose:
                    print(f"Checkpoint saved at plugin {i + 1}")
        
        # Save final checkpoint
        self.save_checkpoint()
        
        # Generate report
        self.generate_report()
        
        # Print summary
        passed = sum(1 for r in self.results if r.status == "passed")
        failed = sum(1 for r in self.results if r.status == "failed")
        skipped = sum(1 for r in self.results if r.status == "skipped")
        
        print(f"\n{'='*50}")
        print(f"Plugin Generation Complete")
        print(f"{'='*50}")
        print(f"Total: {len(self.results)} | Passed: {passed} | Failed: {failed} | Skipped: {skipped}")
        print(f"Time: {time.time() - self.start_time:.2f}s")
        print(f"Cost: ${self.total_cost:.4f}")
        print(f"Report: {REPORT_FILE}")

def main():
    parser = argparse.ArgumentParser(
        description="Plugin Agent CLI for geoChat-v2-core system",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python plugin_agent.py -j specs.json
  python plugin_agent.py --json specs.json --verbose
  python plugin_agent.py -j specs.json --dry-run
  python plugin_agent.py -j specs.json --resume
  python plugin_agent.py -j specs.json --max-plugins 5
        """
    )
    
    parser.add_argument(
        "-j", "--json",
        required=True,
        help="Path to JSON file containing plugin specifications"
    )
    
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose output"
    )
    
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Simulate without making LLM calls"
    )
    
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from last checkpoint"
    )
    
    parser.add_argument(
        "--max-plugins",
        type=int,
        default=None,
        help="Maximum number of plugins to process"
    )
    
    parser.add_argument(
        "--model-cheap",
        default=DEFAULT_MODEL_CHEAP,
        help=f"Model for spec generation (default: {DEFAULT_MODEL_CHEAP})"
    )
    
    parser.add_argument(
        "--model-strong",
        default=DEFAULT_MODEL_STRONG,
        help=f"Model for code generation (default: {DEFAULT_MODEL_STRONG})"
    )
    
    args = parser.parse_args()
    
    # Validate JSON file exists
    if not os.path.exists(args.json):
        print(f"Error: JSON file not found: {args.json}")
        sys.exit(1)
    
    # Create and run agent
    try:
        agent = PluginAgent(args)
        agent.run(args.json)
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()